# Testing this one just a couple of images for now
name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
      'container-review-admin/**'

  containerreview:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: container-review-admin
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      run: docker login -u smarticu5 -p $DOCKER_PASSWORD
    - name: Build the basebuild Docker image
      run: docker build . --file Dockerfile --tag smarticu5/container-review-admin:latest
    - name: Upload basebuild Docker image
      run: docker push smarticu5/container-review-admin:latest
