# Testing this one just a couple of images for now
name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: base_build
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      run: docker login -u smarticu5 -p $DOCKER_PASSWORD
    - name: Build the basebuild Docker image
      run: docker build . --file Dockerfile --tag smarticu5/basebuild:latest
    - name: Upload basebuild Docker image
      run: docker push smarticu5/basebuild:latest
    - name: Docker build the basebuild Python image
      run: docker build . --file Dockerfile-python --tag smarticu5/basebuild:python
