# Testing this one just a couple of images for now
name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      run: docker login -u smarticu5 -p $DOCKER_PASSWORD
    - name: Build the basebuild Docker image
      run: docker build . --file Dockerfile --tag smarticu5/basebuild:latest && docker push smarticu5/basebuild:latest
      working-directory: base_build
    - name: Docker build the basebuild Python image
      run: docker build . --file Dockerfile-python --tag smarticu5/basebuild:python && docker push smarticu5/basebuild:python
      working-directory: base_build